### ISSUE TITLE
Statistic associated with tuple ASM score

### ISSUE THREAD

**Issue by amvondras** [markrobinsonuzh/DAMEfinder#41]
I computed ASM scores for tuples in three samples. 

I'm interested in knowing whether ASM is detected consistently across these replicates.  Can you recommend a way to compute a test statistic for ASM in addition to the ASM score (rather than subsequently testing for gain or loss of ASM with find_dames)?

**Comment by markrobinsonuzh** [comment]
@amvondras 

I don't know what statistical test you would want to do here, because even if replicates, you expect variability.

But, would a plot be useful, like a pairs() plot of the ASM scores across your replicates?

Mark
